# Generated by Django 2.2.4 on 2019-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190828_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='caketang',
            name='total_vote',
            field=models.IntegerField(default=0),
        ),
    ]
