# Generated by Django 2.2.4 on 2019-08-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_caketang_total_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='caketang',
            name='total_vote',
        ),
        migrations.AlterField(
            model_name='caketang',
            name='misi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caketang',
            name='prestasi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caketang',
            name='visi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Token'),
        ),
    ]
