# Generated by Django 2.2.5 on 2019-09-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20190902_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caketang',
            name='ttl',
            field=models.CharField(max_length=40),
        ),
    ]
