# Generated by Django 2.2.4 on 2019-09-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_auto_20190913_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilih',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
