# Generated by Django 2.2.5 on 2019-09-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20190913_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilih',
            name='hasvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='token',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
