# Generated by Django 2.2.4 on 2019-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20190913_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilih',
            name='token',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
